### ISSUE TITLE
Animation doesn't work

### ISSUE THREAD

**Issue by cperfumo** [modweb/meteor-flipclock#1]
Hi there guys,

I've included the FlipClock in a website but the animation doesn't work on Chrome and Firefox. Weirdly enough, when I'm running meteor locally, I can see the animations fine, but when I deploy to production, they don't work (instead, the numbers that are supposed to be animated look quite dark).

Here's the website: https://www.ebrolis.com/pack-ciencia-ficcion

EDIT: At the moment it's working because we disabled CSS minification (we use cloudfare). However, if we enable it, we see the issue.

Any idea how to solve this?

Cheers

**Comment by jfols** [comment]
@cperfumo the [website](https://www.ebrolis.com/pack-ciencia-ficcion) appears to be working properly, I can see flipclock with its usual animations displaying in the latest version of chrome. FYI at this point in Meteor's development you should be using `npm install flipclock` instead of this package--I'll update the readme to say this.
